name: Build & Test

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add musl
      run: rustup target add x86_64-unknown-linux-musl
    - name: Lint
      run: cargo clippy
    - name: Build
      run: cargo build --verbose --release --target x86_64-unknown-linux-musl
    - name: Run tests
      run: cargo test --verbose --release --target x86_64-unknown-linux-musl
