name: Build, Test & Publish

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-publish:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add musl
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: cargo build --verbose --release --target x86_64-unknown-linux-musl
    - name: Run tests
      run: cargo test --verbose --release

    - uses: actions/upload-artifact@v2
      with:
        name: battlesnake
        path: target/release/battlesnake
